### ISSUE TITLE
localhost links in documentation

### ISSUE THREAD

**Issue by slhck** [PcapPlusPlus/pcapplusplus.github.io#8]
In the file https://github.com/PcapPlusPlus/pcapplusplus.github.io/blob/295896f75e1bd919ef8090d4653eb8be731923e3/docs/quickstart/android.md there are two links pointing to `localhost:4000`.

I assume there must have been a bug in auto-generating the correct docs link?

**Comment by seladb** [comment]
Thanks for reporting this issue!
Fixed in both this repo as well as [v21.05](https://github.com/PcapPlusPlus/v2105)
